#!/bin/bash
touch /tmp/file0
sudo apt update -y
touch /tmp/file1
sudo apt install lynx -y
sudo apt install openjdk-8-jre apt-transport-https wget nginx -y
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
touch /tmp/file3
sudo echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" >> /etc/apt/sources.list.d/elastic.list
touch /tmp/file4
sudo apt update -y
touch /tmp/file6
sudo apt install elasticsearch kibana
touch /tmp/file7
sudo systemctl restart kibana
sudo systemctl start elasticsearch
touch /tmp/file8
echo "admin:`openssl passwd -apr1 Azure@123`" | sudo tee -a /etc/nginx/htpasswd.kibana
touch /tmp/file9
