apiVersion: apps/v1
kind: Deployment
metadata:
   name: vzapp1-deploy
spec:
   replicas: 5
   selector:
      matchLabels:
         app: vz-sample
   template:
      metadata:
         labels:
            app: vz-sample
      spec:
         containers:
           - name: vzapp1-container
             image: munireddy1/k8simagenew:v1
             ports:
             - containerPort: 8000
