apiVersion: v1
kind: Service
metadata:
   name: vz-svc
   labels:
      app: vz-sample
spec:
   type: NodePort
   ports:
     - port: 8000
       nodePort: 30133
       protocol: TCP
   selector:
     app: vz-sample
