apiVersion: apps/v1
kind: Deployment
metadata:
   name: czapp1-deploy
spec:
   replicas: 5
   selector:
      matchLabels:
         app: cz-sample
   template:
      metadata:
         labels:
            app: cz-sample
      spec:
         containers:
           - name: czapp1-container
             image: munireddy1/k8simage:v1
             ports:
             - containerPort: 8000
