apiVersion: v1
kind: ReplicationController
metadata:
   name: cz-rc
spec:
   replicas: 10
   selector:
      app: cz-sample
   template:
      metadata:
         labels:
            app: cz-sample
      spec:        
         containers:
           - name: cz-container
             image: munireddy1/k8simage:v1
             ports:
             - containerPort: 8000        
