apiVersion: v1
kind: Service
metadata:
   name: cz-svc
   labels:
      app: cz-sample
spec:
   type: NodePort
   ports:
     - port: 8000
       nodePort: 30133
       protocol: TCP
   selector:
     app: cz-sample
